// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH5HPKweSJSWrst0BG1g2LSv1jpto-ENY',
    appId: '1:717413390455:web:24f333cfe9b9ec39760e72',
    messagingSenderId: '717413390455',
    projectId: 'finanzas-ab3d4',
    authDomain: 'finanzas-ab3d4.firebaseapp.com',
    storageBucket: 'finanzas-ab3d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcebYySMV-HMuSuyNW2YiSqU6S4t4G_wM',
    appId: '1:717413390455:android:1114a1ec8c9a4ee0760e72',
    messagingSenderId: '717413390455',
    projectId: 'finanzas-ab3d4',
    storageBucket: 'finanzas-ab3d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-fQ5KxIrwwUEDhgzkYa2jcW8SYypDB8',
    appId: '1:717413390455:ios:5aaf18001a14c91c760e72',
    messagingSenderId: '717413390455',
    projectId: 'finanzas-ab3d4',
    storageBucket: 'finanzas-ab3d4.appspot.com',
    iosBundleId: 'com.example.proyectoFinanzas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB-fQ5KxIrwwUEDhgzkYa2jcW8SYypDB8',
    appId: '1:717413390455:ios:b22cd01f1b81006f760e72',
    messagingSenderId: '717413390455',
    projectId: 'finanzas-ab3d4',
    storageBucket: 'finanzas-ab3d4.appspot.com',
    iosBundleId: 'com.example.proyectoFinanzas.RunnerTests',
  );
}
